name: Build YunImage Server

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-20.04 
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
          fetch-submodules: true

      - name: Initialize Go Module
        run: |
          go mod init YunImage
          go mod tidy

      - name: Build YunImage
        run: go build -v -o YunImage .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "YunImage Server ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./YunImage
          asset_name: YunImage
          asset_content_type: application/octet-stream

  build-windows:
    runs-on: windows-latest  # 仅使用Windows操作系统
    needs: build-linux  # 确保在build-linux作业之后运行
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
          architecture: x64  # 确保下载64位版本的Go
          fetch-submodules: true

      - name: Initialize Go Module
        run: |
          go mod init YunImage
          go mod tidy

      - name: Build YunImage
        run: |
          go build -v -o YunImage.exe .

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build-linux.outputs.upload_url }}
          asset_path: ./YunImage.exe
          asset_name: YunImage.exe
          asset_content_type: application/octet-stream